### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by iProgYou** [chrisaugust29/myhelpapp#5]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
- Check the schema comments. You may need some more info in businesses. If a business only has one category, you can just put the category within each business. Happy to talk about this further.
- I would recommend having a reviewIds array within each business in the business slice of state to keep track of all of the related reviews

**Comment by iProgYou** [comment]
- If you are doing a joins table for your categories, then you will need an array of `category_ids` within each business.

**Comment by chrisaugust29** [comment]
added category id in my business

**Comment by iProgYou** [comment]
Since each business will have potentially several categories associated, you will need each business to have an array of `categoryIds`. You may also want to remove the `category` from each business, unless you want there to be a primary category.

**Comment by chrisaugust29** [comment]
updated to array of category Ids and removed category
